### model
model_name_or_path: /root/Meta-Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: datasets
dataset: mol_retrosynthesis_train,ChemDual_fragment_train,ChemDual_recombination_train
template: llama3
cutoff_len: 1024
max_samples: 130000
overwrite_cache: true
preprocessing_num_workers: 48

### output
output_dir: saves/ChemDual/additional/ChemDual_w_o_forwardv1
logging_steps: 10
save_steps: 1000
plot_loss: true
# overwrite_output_dir: true

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 3
eval_strategy: steps
eval_steps: 2000
